# Generated by Django 4.1.3 on 2022-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buser',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False, verbose_name=int)),
                ('email', models.TextField(verbose_name=120)),
                ('nickname', models.TextField(verbose_name=20)),
                ('password', models.TextField(verbose_name=255)),
            ],
            options={
                'db_table': 'busers',
            },
        ),
    ]
